import type { Metadata } from 'next';
import { nato_sans_kr } from '@/app/ui/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={nato_sans_kr.className}>
      <body>{children}</body>
    </html>
  );
}
